### ISSUE TITLE
Leak in OS X Lion

### ISSUE THREAD

**Issue by simplydesigner** [fortinmike/Regexer#1]
objc[560]: Object 0x100114a30 of class __NSMutableDictionary autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug.

Replace + (void) load to + (void) initialize

**Comment by fortinmike** [comment]
Thanks for reporting this. Can you please submit a pull request with the proposed fix? I'll take a look as soon as I can.

**Comment by JanX2** [comment]
I have probably fixed this with my PR #2.

**Comment by fortinmike** [comment]
I can't confirm this easily, so I'll close the issue for now. Please comment if this isn't fixed and I'll re-open.
